- name: Check os version and family
  fail:
      msg: "This role can only be run against Debian 9 Stretch. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - ansible_os_family == 'Debian'
      - ansible_distribution_major_version | version('9', '!=')
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.5 or greater
  when: not ansible_version.full | version('2.5', '>=')
  tags:
      - always

- name: Load in variables file
  include_vars: "master-vars.yml"

- include: master-bootstrap.yml
  become: yes
  tags:
    - master-bootstrap
    - always
