---
# handlers file for kube-master

- name: docker status
  service:
    name: docker
    state: started
    enabled: true

- name: Wait for cache updates
  become: yes
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;

# - name: apt-get update
#   apt:
#     update_cache: yes
#   register: apt_res
#   retries: 5
#   until: apt_res is success